//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookObjectives.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Objective", Namespace="http://www.intacomputers.com/Services/Objectives/")]
    [System.SerializableAttribute()]
    public partial class Objective : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectiveNameField;
        
        private System.DateTime CreatedField;
        
        private bool ArchivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ObjectiveName {
            get {
                return this.ObjectiveNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectiveNameField, value) != true)) {
                    this.ObjectiveNameField = value;
                    this.RaisePropertyChanged("ObjectiveName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Archived {
            get {
                return this.ArchivedField;
            }
            set {
                if ((this.ArchivedField.Equals(value) != true)) {
                    this.ArchivedField = value;
                    this.RaisePropertyChanged("Archived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientList", Namespace="http://www.intacomputers.com/Services/Objectives/")]
    [System.SerializableAttribute()]
    public partial class ClientList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OutlookObjectives.ServiceReference1.Client[] ClientsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public OutlookObjectives.ServiceReference1.Client[] Clients {
            get {
                return this.ClientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientsField, value) != true)) {
                    this.ClientsField = value;
                    this.RaisePropertyChanged("Clients");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://www.intacomputers.com/Services/Objectives/")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EntryId {
            get {
                return this.EntryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryIdField, value) != true)) {
                    this.EntryIdField = value;
                    this.RaisePropertyChanged("EntryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.intacomputers.com/Services/Objectives/", ConfigurationName="ServiceReference1.ObjectivesSoap")]
    public interface ObjectivesSoap {
        
        // CODEGEN: Generating message contract since element name objective from namespace http://www.intacomputers.com/Services/Objectives/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intacomputers.com/Services/Objectives/SaveObjective", ReplyAction="*")]
        OutlookObjectives.ServiceReference1.SaveObjectiveResponse SaveObjective(OutlookObjectives.ServiceReference1.SaveObjectiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intacomputers.com/Services/Objectives/SaveObjective", ReplyAction="*")]
        System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.SaveObjectiveResponse> SaveObjectiveAsync(OutlookObjectives.ServiceReference1.SaveObjectiveRequest request);
        
        // CODEGEN: Generating message contract since element name GetClientListResult from namespace http://www.intacomputers.com/Services/Objectives/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intacomputers.com/Services/Objectives/GetClientList", ReplyAction="*")]
        OutlookObjectives.ServiceReference1.GetClientListResponse GetClientList(OutlookObjectives.ServiceReference1.GetClientListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intacomputers.com/Services/Objectives/GetClientList", ReplyAction="*")]
        System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.GetClientListResponse> GetClientListAsync(OutlookObjectives.ServiceReference1.GetClientListRequest request);
        
        // CODEGEN: Generating message contract since element name clientList from namespace http://www.intacomputers.com/Services/Objectives/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intacomputers.com/Services/Objectives/SetClientList", ReplyAction="*")]
        OutlookObjectives.ServiceReference1.SetClientListResponse SetClientList(OutlookObjectives.ServiceReference1.SetClientListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intacomputers.com/Services/Objectives/SetClientList", ReplyAction="*")]
        System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.SetClientListResponse> SetClientListAsync(OutlookObjectives.ServiceReference1.SetClientListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveObjectiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveObjective", Namespace="http://www.intacomputers.com/Services/Objectives/", Order=0)]
        public OutlookObjectives.ServiceReference1.SaveObjectiveRequestBody Body;
        
        public SaveObjectiveRequest() {
        }
        
        public SaveObjectiveRequest(OutlookObjectives.ServiceReference1.SaveObjectiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.intacomputers.com/Services/Objectives/")]
    public partial class SaveObjectiveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OutlookObjectives.ServiceReference1.Objective objective;
        
        public SaveObjectiveRequestBody() {
        }
        
        public SaveObjectiveRequestBody(OutlookObjectives.ServiceReference1.Objective objective) {
            this.objective = objective;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveObjectiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveObjectiveResponse", Namespace="http://www.intacomputers.com/Services/Objectives/", Order=0)]
        public OutlookObjectives.ServiceReference1.SaveObjectiveResponseBody Body;
        
        public SaveObjectiveResponse() {
        }
        
        public SaveObjectiveResponse(OutlookObjectives.ServiceReference1.SaveObjectiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveObjectiveResponseBody {
        
        public SaveObjectiveResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientList", Namespace="http://www.intacomputers.com/Services/Objectives/", Order=0)]
        public OutlookObjectives.ServiceReference1.GetClientListRequestBody Body;
        
        public GetClientListRequest() {
        }
        
        public GetClientListRequest(OutlookObjectives.ServiceReference1.GetClientListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClientListRequestBody {
        
        public GetClientListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientListResponse", Namespace="http://www.intacomputers.com/Services/Objectives/", Order=0)]
        public OutlookObjectives.ServiceReference1.GetClientListResponseBody Body;
        
        public GetClientListResponse() {
        }
        
        public GetClientListResponse(OutlookObjectives.ServiceReference1.GetClientListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.intacomputers.com/Services/Objectives/")]
    public partial class GetClientListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OutlookObjectives.ServiceReference1.ClientList GetClientListResult;
        
        public GetClientListResponseBody() {
        }
        
        public GetClientListResponseBody(OutlookObjectives.ServiceReference1.ClientList GetClientListResult) {
            this.GetClientListResult = GetClientListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetClientListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetClientList", Namespace="http://www.intacomputers.com/Services/Objectives/", Order=0)]
        public OutlookObjectives.ServiceReference1.SetClientListRequestBody Body;
        
        public SetClientListRequest() {
        }
        
        public SetClientListRequest(OutlookObjectives.ServiceReference1.SetClientListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.intacomputers.com/Services/Objectives/")]
    public partial class SetClientListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OutlookObjectives.ServiceReference1.ClientList clientList;
        
        public SetClientListRequestBody() {
        }
        
        public SetClientListRequestBody(OutlookObjectives.ServiceReference1.ClientList clientList) {
            this.clientList = clientList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetClientListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetClientListResponse", Namespace="http://www.intacomputers.com/Services/Objectives/", Order=0)]
        public OutlookObjectives.ServiceReference1.SetClientListResponseBody Body;
        
        public SetClientListResponse() {
        }
        
        public SetClientListResponse(OutlookObjectives.ServiceReference1.SetClientListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetClientListResponseBody {
        
        public SetClientListResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ObjectivesSoapChannel : OutlookObjectives.ServiceReference1.ObjectivesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectivesSoapClient : System.ServiceModel.ClientBase<OutlookObjectives.ServiceReference1.ObjectivesSoap>, OutlookObjectives.ServiceReference1.ObjectivesSoap {
        
        public ObjectivesSoapClient() {
        }
        
        public ObjectivesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjectivesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectivesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectivesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutlookObjectives.ServiceReference1.SaveObjectiveResponse OutlookObjectives.ServiceReference1.ObjectivesSoap.SaveObjective(OutlookObjectives.ServiceReference1.SaveObjectiveRequest request) {
            return base.Channel.SaveObjective(request);
        }
        
        public void SaveObjective(OutlookObjectives.ServiceReference1.Objective objective) {
            OutlookObjectives.ServiceReference1.SaveObjectiveRequest inValue = new OutlookObjectives.ServiceReference1.SaveObjectiveRequest();
            inValue.Body = new OutlookObjectives.ServiceReference1.SaveObjectiveRequestBody();
            inValue.Body.objective = objective;
            OutlookObjectives.ServiceReference1.SaveObjectiveResponse retVal = ((OutlookObjectives.ServiceReference1.ObjectivesSoap)(this)).SaveObjective(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.SaveObjectiveResponse> OutlookObjectives.ServiceReference1.ObjectivesSoap.SaveObjectiveAsync(OutlookObjectives.ServiceReference1.SaveObjectiveRequest request) {
            return base.Channel.SaveObjectiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.SaveObjectiveResponse> SaveObjectiveAsync(OutlookObjectives.ServiceReference1.Objective objective) {
            OutlookObjectives.ServiceReference1.SaveObjectiveRequest inValue = new OutlookObjectives.ServiceReference1.SaveObjectiveRequest();
            inValue.Body = new OutlookObjectives.ServiceReference1.SaveObjectiveRequestBody();
            inValue.Body.objective = objective;
            return ((OutlookObjectives.ServiceReference1.ObjectivesSoap)(this)).SaveObjectiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutlookObjectives.ServiceReference1.GetClientListResponse OutlookObjectives.ServiceReference1.ObjectivesSoap.GetClientList(OutlookObjectives.ServiceReference1.GetClientListRequest request) {
            return base.Channel.GetClientList(request);
        }
        
        public OutlookObjectives.ServiceReference1.ClientList GetClientList() {
            OutlookObjectives.ServiceReference1.GetClientListRequest inValue = new OutlookObjectives.ServiceReference1.GetClientListRequest();
            inValue.Body = new OutlookObjectives.ServiceReference1.GetClientListRequestBody();
            OutlookObjectives.ServiceReference1.GetClientListResponse retVal = ((OutlookObjectives.ServiceReference1.ObjectivesSoap)(this)).GetClientList(inValue);
            return retVal.Body.GetClientListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.GetClientListResponse> OutlookObjectives.ServiceReference1.ObjectivesSoap.GetClientListAsync(OutlookObjectives.ServiceReference1.GetClientListRequest request) {
            return base.Channel.GetClientListAsync(request);
        }
        
        public System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.GetClientListResponse> GetClientListAsync() {
            OutlookObjectives.ServiceReference1.GetClientListRequest inValue = new OutlookObjectives.ServiceReference1.GetClientListRequest();
            inValue.Body = new OutlookObjectives.ServiceReference1.GetClientListRequestBody();
            return ((OutlookObjectives.ServiceReference1.ObjectivesSoap)(this)).GetClientListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutlookObjectives.ServiceReference1.SetClientListResponse OutlookObjectives.ServiceReference1.ObjectivesSoap.SetClientList(OutlookObjectives.ServiceReference1.SetClientListRequest request) {
            return base.Channel.SetClientList(request);
        }
        
        public void SetClientList(OutlookObjectives.ServiceReference1.ClientList clientList) {
            OutlookObjectives.ServiceReference1.SetClientListRequest inValue = new OutlookObjectives.ServiceReference1.SetClientListRequest();
            inValue.Body = new OutlookObjectives.ServiceReference1.SetClientListRequestBody();
            inValue.Body.clientList = clientList;
            OutlookObjectives.ServiceReference1.SetClientListResponse retVal = ((OutlookObjectives.ServiceReference1.ObjectivesSoap)(this)).SetClientList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.SetClientListResponse> OutlookObjectives.ServiceReference1.ObjectivesSoap.SetClientListAsync(OutlookObjectives.ServiceReference1.SetClientListRequest request) {
            return base.Channel.SetClientListAsync(request);
        }
        
        public System.Threading.Tasks.Task<OutlookObjectives.ServiceReference1.SetClientListResponse> SetClientListAsync(OutlookObjectives.ServiceReference1.ClientList clientList) {
            OutlookObjectives.ServiceReference1.SetClientListRequest inValue = new OutlookObjectives.ServiceReference1.SetClientListRequest();
            inValue.Body = new OutlookObjectives.ServiceReference1.SetClientListRequestBody();
            inValue.Body.clientList = clientList;
            return ((OutlookObjectives.ServiceReference1.ObjectivesSoap)(this)).SetClientListAsync(inValue);
        }
    }
}
